### PR TITLE
PSR-2

### PR DESCRIPTION
**Pull request by xbuzz**
Bring the code base into line with the PHP-FIG [PSR-2](http://www.php-fig.org/psr/psr-2/).

### CODE REVIEW

**Comment by xbuzz** [comment]
I realize that there was a previous request for PSR-1 but this should help further enhance readability. #2

**Comment by illblew** [comment]
Bah, just pushed some changes from last night and caused conflicts :(

**Comment by illblew** [comment]
I'll try to hash this out during non-work hours if you don't get there first. Looks good to go aside from my conflicting changes.

**Comment by xbuzz** [comment]
@illblew No sweat. Rebased and fixed the changes to save you some time.

**Comment by illblew** [comment]
Nice, I'll try to reduce the sloppy in future commits.

**Pull request merged**
